
import java.awt.AWTException;
import java.awt.Desktop;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Robot;
import static java.awt.SystemColor.menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JApplet;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fatema
 */
public class Desktop_page extends javax.swing.JFrame {

    /**
     * Creates new form Desktop_page
     */int xMouse;
    int yMouse;
    int xMouse1;
    int yMouse1;
    int xMouse2;
    int yMouse2;
    int x2;
    int y2;
    private JButton powerButton, slp, sdown, restart;
    final JPopupMenu menu = new JPopupMenu("Menu");
    
    
    public Desktop_page ()  {
        initComponents();
        showDate();
        showTime();
    }
   //slp = new jL("----Sleep-----");
       
//        menu.add(slp);
//        //sdown = new JButton("-ShutDown-");
//        
//        menu.add(sdown);
//      //restart = new JButton("---Restart---");
//        
//        menu.add(restart);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 900));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mycomupter.PNG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/recycle bin.PNG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 80, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Folders-OS-Windows-8-Metro-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 720, 80, 48);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1260, 740, 80, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1260, 720, 80, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fileexplore.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 720, 59, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/speaker-icon.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1200, 730, 40, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wifi1.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1150, 730, 60, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/battary1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1110, 740, 30, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shut down.PNG"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel12, org.jdesktop.beansbinding.ELProperty.create("${componentPopupMenu.componentPopupMenu}"), jLabel12, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
                sleep(evt);
                shutdown(evt);
                Restart(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1280, 130, 70, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baground.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-290, -30, 2680, 750);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mozila2.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 720, 70, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tskbar.PNG"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 700, 1360, 100);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1280, 150, 70, 50);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       try {
            
            Process p = Runtime.getRuntime().exec("cmd /c start shell:mycomputerfolder");
        } catch (IOException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            // TODO add your handling code here
            Process p = Runtime.getRuntime().exec("cmd /c start shell:RecycleBinFolder");
            p.waitFor();
        } catch (IOException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        Robot robo = null;
        try {
            robo = new Robot(gd);
        } catch (AWTException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
        robo.setAutoDelay(100);
        robo.keyPress(KeyEvent.VK_WINDOWS);
       robo.keyRelease(KeyEvent.VK_WINDOWS);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
      // int x2 = evt.getX();
      // int y2 = evt.getY();
        jLabel1.setLocation((x-x2)-(xMouse1-xMouse),(y-y2)-(yMouse1-yMouse));
         // System.out.println(  x-xMouse2);
       jLabel1.setVisible(true);    
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
      // int x2 = evt.getX();
      // int y2 = evt.getY();
        jLabel2.setLocation((x-x2)-(xMouse1-xMouse),(y-y2)-(yMouse1-yMouse));
         // System.out.println(  x-xMouse2);
       jLabel2.setVisible(true);    
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xMouse1 = evt.getX();
        yMouse1 = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       try {
             Process p=Runtime.getRuntime().exec("explorer.exe");
            //Process p = new ProcessBuilder("C:\Program Files (x86)\Mozilla Firefox\\firefox").start();
        } catch (IOException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
      // int x2 = evt.getX();
      // int y2 = evt.getY();
        jLabel6.setLocation((x-x2)-(xMouse1-xMouse),(y-y2)-(yMouse1-yMouse));
         // System.out.println(  x-xMouse2);
       jLabel6.setVisible(true); 
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        xMouse1 = evt.getX();
        yMouse1 = evt.getY();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
slp = new JButton("----Sleep-----");
 menu.add(slp);
 
        sdown = new JButton("-ShutDown-");
        
        menu.add(sdown);
      restart = new JButton("---Restart---");
        
        menu.add(restart);

//        slp.addActionListener((ActionListener) this);
//        sdown.addActionListener(this);
//        restart.addActionListener(this);
Runtime runtime = Runtime.getRuntime();
            menu.show(powerButton, powerButton.getWidth() / 2, powerButton.getHeight() / 2);
       
        if (evt.getSource() == slp) {
            try {
                Runtime.getRuntime().exec("Rundll32.exe powrprof.dll,SetSuspendState Sleep");
            } catch (IOException ex) {

            }
        } else if (evt.getSource() == sdown) {
           
            try {

                Process proc = runtime.exec("shutdown -s -t 0");
            } catch (IOException ex) {

            }
            System.exit(0);
        } else if (evt.getSource() == restart) {
          
            try {

                Process proc = runtime.exec("shutdown -r -t 0");
            } catch (IOException ex) {

            }
            System.exit(0);
        }

    

    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        try {
             //Process p=Runtime.getRuntime().exec("explorer.exe");
            Process p = new ProcessBuilder("C:\\Program Files (x86)\\Mozilla Firefox\\firefox").start();
        } catch (IOException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void sleep(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleep
      
            // jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shut down.PNG");
//             Runtime runtime = Runtime.getRuntime();
//              try {
//                Runtime.getRuntime().exec("Rundll32.exe powrprof.dll,SetSuspendState Sleep");
//            } catch (IOException ex) {
//
//            }
             
             
    }//GEN-LAST:event_sleep

    private void shutdown(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdown
//         Runtime runtime = Runtime.getRuntime();
//            try {
//
//                Process proc = runtime.exec("shutdown -s -t 0");
//            } catch (IOException ex) {
//
//            }
//            System.exit(0);
    }//GEN-LAST:event_shutdown

    private void Restart(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Restart
//        Runtime runtime = Runtime.getRuntime();
//            try {
//
//                Process proc = runtime.exec("shutdown -r -t 0");
//            } catch (IOException ex) {
//
//            }
//            System.exit(0);
    }//GEN-LAST:event_Restart

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop_page().setVisible(true);
            }
        });
    }
    void showTime(){
    
    new Timer(0 , new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            Date d = new Date();
           
            
    
    SimpleDateFormat t = new SimpleDateFormat("HH:mm:ss a");

    jLabel5.setText(t.format(d));
    
   
  
        }
    }).start();
    
}
      void showDate(){
    Date d = new Date();
    SimpleDateFormat D = new SimpleDateFormat("dd-MM-YYYY");
    jLabel4.setText(D.format(d));
    
    
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}

